
development:
    adapter: postgresql
    host: localhost
    database: vidhata_cranes_development
    username: postgres
    password: scorp

test:
    adapter: postgresql
    host: localhost
    database: vidhata_cranes_test
    username: postgres
    password: scorp

production:
    adapter: postgresql
    host: localhost
    database: vidhata_cranes_production
    username: postgres
    password: scorp
    reconnect: true
